### ISSUE TITLE
A better name?

### ISSUE THREAD

**Issue by bagder** [curl/urler#1]
Proposals that have been mentioned:

- trurl
- purlmutate
- manipurler
- manipurlate
- curlify
- urlwtf
- crurl
- purl
- urlchop
- burl
- unfURL
- urlchemy
- manipURLator

**Comment by jezdez** [comment]
uq similar to [jq](https://stedolan.github.io/jq/)?

**Comment by Ainali** [comment]
- AltURL
- ConvURL

**Comment by McSinyx** [comment]
I like the current one, it's how URL is spelled out (informally) in my native tongue.

**Comment by sharponlooker** [comment]
churl

**Comment by foosel** [comment]
url query -> urlq -> urql?

I also like the already suggested trurl

**Comment by daenney** [comment]
Querying URL(s) -> `qurl`, pronounced like curl.

**Comment by hollerith** [comment]
urlne :stuck_out_tongue_closed_eyes:

**Comment by jpmens** [comment]
`hurl`. 

Same length as `curl`, could mean `h`andy URL, and means any of throw, toss, fling, launch which sounds nice. To me.

*lets himself out*

**Comment by Awesomolocity** [comment]
SeeURL

**Comment by polaris64** [comment]
How about cURL, for "change URL"... Oh, wait...

**Comment by bouncepaw** [comment]
uq or keep urler

**Comment by gregswift** [comment]
Url parser > `up` ?

**Comment by bricewge** [comment]
> uq similar to [jq](https://stedolan.github.io/jq/)?

Distros usually frown upon new software with really short names.

> Url parser > up ?

Same.

> hurl.

There is already a quite handy test tool names [hurl](https://github.com/Orange-OpenSource/hurl). It describes itself as `Hurl, run and test HTTP requests with plain text.`.

**Comment by artlog** [comment]
urlhandy urlcoach

**Comment by kiranb83** [comment]
urlgrok => `ug`
grokurl => `gurl`

> When you grok something, you just get it — in other words, you totally grasp its meaning.

ref: [vocabulary.com](https://www.vocabulary.com/dictionary/grok)

**Comment by bagder** [comment]
I'm amazed by the number of really excellent name suggestions that are pouring in. It makes it really hard to decide...

**Comment by bch** [comment]
curle (, curl-e, curly).

“curl [url] extractor”. Not a homonym like qurl (so easy to communicate in speech), but  related to curl, concise, fun.

**Comment by przemoc** [comment]
> SeeURL

Had the same idea, but without capitalization:

seeURL

**Comment by ajorg** [comment]
+1 to purl

I like how it complements curl so nicely, and it's already a word I associate with URL parsing because I've used it as a variable name to store parsed URLs in Python programs.

**Comment by futzle** [comment]
murl (“m”anipulate) already seems to be taken, sadly. 

+1 for unfurl, or even just furl because it can construct as well as deconstruct URLs.

**Comment by Be-ing** [comment]
[Bueller?](https://www.youtube.com/watch?v=_u6OYuiTJsc)

**Comment by ajorg** [comment]
urql

**Comment by bjornwarmedal** [comment]
How about 
* murlin
Because dealing with URLs is a bit magic sometimes.

**Comment by infotexture** [comment]
`url8` urelate You relate?

**Comment by TABHIRAM** [comment]
Url360

**Comment by TABHIRAM** [comment]
url360

**Comment by asbjornu** [comment]
Just out of curiosity, what's the reasoning behind `trurl`?

**Comment by marcin-gryszkalis** [comment]
Just fyi - Trulr is well known name among hardcore SF readers as it's name of character in Lem's Cyberiad book (1965) - another reason to like the name :) 
- https://en.wikipedia.org/wiki/The_Cyberiad
- https://www.goodreads.com/characters/45641-trurl
