### ISSUE TITLE
more fine-grained output option

### ISSUE THREAD

**Issue by bagder** [curl/urler#10]
for example like curl's -w option that allows using percent signs and variable names in braces for a slightly verbose, but printf-like DSL. Very common options like formatting `{scheme}://{host}` may even be given a long flag to print.

(from [Tunapunk](https://mastodon.social/@wasamasa@lonely.town/110117305947256046))

**Comment by cbandy** [comment]
I like this idea as well. Reminds me of `printf`, so a name like `--format` is intuitive to me.

🤔 Perhaps its functionality is a superset of the `--get` flags, allowing them to go away altogether? How different are the following experiences?

```console
$ tool --get '{scheme}' 'https://curl.se/'
https
$ tool --get-scheme 'https://curl.se/'
https
```

**Comment by bagder** [comment]
Oh, that's neat!

**Comment by bagder** [comment]
I thought more about this proposal and I would like to hear more about the possible use cases. I fear this might encourage users down the wrong path (like trying to create a new URL using the output format)).

Should we not rather encourage users to blank out the parts they don't to keep and then just output the full URL? Like if you want to remove the user and password from a URL and keep everything else:

~~~
$ tool https://user:secret@example.com/index.html --set-user "" --set-password ""
https://example.com/index.html

**Comment by dfandrich** [comment]
I can think of lots of use cases for outputting less than a full URL but more
than just one part. How about extracting the hostname+port to perform a
certificate check? Extracting the host+path to map to a local file on a vhost?
How about embedding one part in other text to convert it into a more useful
form, such as including double quotes and commas to make it CSV, or in curly
brackets to make JSON?  It's too useful a feature to not add :-)

**Comment by bagder** [comment]
I'm sold. Let's add this. Thanks! :green_heart:
