### ISSUE TITLE
Build path component from multiple segments

### ISSUE THREAD

**Issue by cbandy** [curl/urler#12]
I find myself working with "base" URLs from time to time that already have a `path` component. It would be nice if there were a way to "extend" the `path` of a URL more intelligently than I can with shell string concatenation.

Maybe something like the following:

```console
$ tool --segment 'a' --segment '/' 'https://github.com/b'
https://github.com/b/a/%2F
```

**Comment by bagder** [comment]
I think we want to support that with query parts as well. Like when you want to add `a=foo` and `b=moo`, and make sure they are URL encoded and separated with an ampersand (`&`):

~~~
$ tool https://example.com --yada a=foo --yada "b=foo bar"
https://example.com/?a=foo&b=foo%20bar

**Comment by bagder** [comment]
`--append-path` and `--append-query` maybe?

**Comment by bagder** [comment]
Both of these are now supported.
