### ISSUE TITLE
Multiple URLs and/or STDIN

### ISSUE THREAD

**Issue by cbandy** [curl/urler#13]
~Only one URL can be manipulated per invocation using the `--url` flag.~ It may be useful to manipulate more than one.

I have yet to find a specific use case, so this seems more like a UX thing. It seems natural that a focused utility like this would accept its "main" input as non-flag arguments or via standard input. For example:

```console
$ tool --set-user myself 'https://github.com' 'ftp://google.com'
https://myself@github.com
ftp://myself@google.com
```

It's not uncommon for "no arguments" to cause a utility to read from STDIN, but in my experience, that can allow mistakes to cause hung scripts. A good balance, I think, is some "file" flag that uses `-` to mean STDIN:

```console
$ echo 'https://github.com' > data.txt
$ echo 'ftp://google.com' >> data.txt
$ tool --set-user myself --file data.txt
https://myself@github.com
ftp://myself@google.com
```

```console
$ echo '[{"url": "https://github.com"}, {"url": "ftp://google.com"}]' > data.json
$ jq -r .[].url data.json | tool --set-user myself --file -
https://myself@github.com
ftp://myself@google.com
```

**Comment by bagder** [comment]
Yes, applying everything to multiple URLs seems easy enough.

If we should read a number of URLs from stdin or a file, I think we should probably call the option `--url-file` or something so that we keep the option open for using files in more ways in the future.

**Comment by bagder** [comment]
Since 1c164e7487f it now supports multiple URLs on the command line.

**Comment by bagder** [comment]
I think I'll hold off the stdin play for now. It is easy to use xargs for that for now.
